package org.bouncycastle.asn1.bc;

import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* JADX INFO: loaded from: classes2.dex */
public interface BCObjectIdentifiers {
    public static final ASN1ObjectIdentifier bc;
    public static final ASN1ObjectIdentifier bc_exch;
    public static final ASN1ObjectIdentifier bc_ext;
    public static final ASN1ObjectIdentifier bc_kem;
    public static final ASN1ObjectIdentifier bc_pbe;
    public static final ASN1ObjectIdentifier bc_pbe_sha1;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha1_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha224;
    public static final ASN1ObjectIdentifier bc_pbe_sha256;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes128_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes192_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs12_aes256_cbc;
    public static final ASN1ObjectIdentifier bc_pbe_sha256_pkcs5;
    public static final ASN1ObjectIdentifier bc_pbe_sha384;
    public static final ASN1ObjectIdentifier bc_pbe_sha512;
    public static final ASN1ObjectIdentifier bc_sig;
    public static final ASN1ObjectIdentifier external_value;
    public static final ASN1ObjectIdentifier firesaberkem128r3;
    public static final ASN1ObjectIdentifier firesaberkem192r3;
    public static final ASN1ObjectIdentifier firesaberkem256r3;
    public static final ASN1ObjectIdentifier frodokem19888r3;
    public static final ASN1ObjectIdentifier frodokem19888shaker3;
    public static final ASN1ObjectIdentifier frodokem31296r3;
    public static final ASN1ObjectIdentifier frodokem31296shaker3;
    public static final ASN1ObjectIdentifier frodokem43088r3;
    public static final ASN1ObjectIdentifier frodokem43088shaker3;
    public static final ASN1ObjectIdentifier lightsaberkem128r3;
    public static final ASN1ObjectIdentifier lightsaberkem192r3;
    public static final ASN1ObjectIdentifier lightsaberkem256r3;
    public static final ASN1ObjectIdentifier linkedCertificate;
    public static final ASN1ObjectIdentifier mceliece348864_r3;
    public static final ASN1ObjectIdentifier mceliece348864f_r3;
    public static final ASN1ObjectIdentifier mceliece460896_r3;
    public static final ASN1ObjectIdentifier mceliece460896f_r3;
    public static final ASN1ObjectIdentifier mceliece6688128_r3;
    public static final ASN1ObjectIdentifier mceliece6688128f_r3;
    public static final ASN1ObjectIdentifier mceliece6960119_r3;
    public static final ASN1ObjectIdentifier mceliece6960119f_r3;
    public static final ASN1ObjectIdentifier mceliece8192128_r3;
    public static final ASN1ObjectIdentifier mceliece8192128f_r3;
    public static final ASN1ObjectIdentifier newHope;
    public static final ASN1ObjectIdentifier pqc_kem_frodo;
    public static final ASN1ObjectIdentifier pqc_kem_mceliece;
    public static final ASN1ObjectIdentifier pqc_kem_saber;
    public static final ASN1ObjectIdentifier qTESLA;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_size;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_III_speed;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_I;
    public static final ASN1ObjectIdentifier qTESLA_Rnd1_p_III;
    public static final ASN1ObjectIdentifier qTESLA_p_I;
    public static final ASN1ObjectIdentifier qTESLA_p_III;
    public static final ASN1ObjectIdentifier saberkem128r3;
    public static final ASN1ObjectIdentifier saberkem192r3;
    public static final ASN1ObjectIdentifier saberkem256r3;
    public static final ASN1ObjectIdentifier sphincs256;
    public static final ASN1ObjectIdentifier sphincs256_with_BLAKE512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA3_512;
    public static final ASN1ObjectIdentifier sphincs256_with_SHA512;
    public static final ASN1ObjectIdentifier sphincsPlus;
    public static final ASN1ObjectIdentifier sphincsPlus_sha_256;
    public static final ASN1ObjectIdentifier sphincsPlus_sha_512;
    public static final ASN1ObjectIdentifier sphincsPlus_shake_256;
    public static final ASN1ObjectIdentifier xmss;
    public static final ASN1ObjectIdentifier xmss_SHA256;
    public static final ASN1ObjectIdentifier xmss_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_SHA512;
    public static final ASN1ObjectIdentifier xmss_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_SHA256ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_SHA512ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE128ph;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_mt_SHAKE256ph;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_mt_with_SHAKE256;
    public static final ASN1ObjectIdentifier xmss_with_SHA256;
    public static final ASN1ObjectIdentifier xmss_with_SHA512;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE128;
    public static final ASN1ObjectIdentifier xmss_with_SHAKE256;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.3.6.1.4.1.22554");
        bc = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = aSN1ObjectIdentifier.branch("1");
        bc_pbe = aSN1ObjectIdentifierBranch;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = aSN1ObjectIdentifierBranch.branch("1");
        bc_pbe_sha1 = aSN1ObjectIdentifierBranch2;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch3 = aSN1ObjectIdentifierBranch.branch("2.1");
        bc_pbe_sha256 = aSN1ObjectIdentifierBranch3;
        bc_pbe_sha384 = aSN1ObjectIdentifierBranch.branch("2.2");
        bc_pbe_sha512 = aSN1ObjectIdentifierBranch.branch("2.3");
        bc_pbe_sha224 = aSN1ObjectIdentifierBranch.branch("2.4");
        bc_pbe_sha1_pkcs5 = aSN1ObjectIdentifierBranch2.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch4 = aSN1ObjectIdentifierBranch2.branch("2");
        bc_pbe_sha1_pkcs12 = aSN1ObjectIdentifierBranch4;
        bc_pbe_sha256_pkcs5 = aSN1ObjectIdentifierBranch3.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch5 = aSN1ObjectIdentifierBranch3.branch("2");
        bc_pbe_sha256_pkcs12 = aSN1ObjectIdentifierBranch5;
        bc_pbe_sha1_pkcs12_aes128_cbc = aSN1ObjectIdentifierBranch4.branch("1.2");
        bc_pbe_sha1_pkcs12_aes192_cbc = aSN1ObjectIdentifierBranch4.branch("1.22");
        bc_pbe_sha1_pkcs12_aes256_cbc = aSN1ObjectIdentifierBranch4.branch("1.42");
        bc_pbe_sha256_pkcs12_aes128_cbc = aSN1ObjectIdentifierBranch5.branch("1.2");
        bc_pbe_sha256_pkcs12_aes192_cbc = aSN1ObjectIdentifierBranch5.branch("1.22");
        bc_pbe_sha256_pkcs12_aes256_cbc = aSN1ObjectIdentifierBranch5.branch("1.42");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch6 = aSN1ObjectIdentifier.branch("2");
        bc_sig = aSN1ObjectIdentifierBranch6;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch7 = aSN1ObjectIdentifierBranch6.branch("1");
        sphincs256 = aSN1ObjectIdentifierBranch7;
        sphincs256_with_BLAKE512 = aSN1ObjectIdentifierBranch7.branch("1");
        sphincs256_with_SHA512 = aSN1ObjectIdentifierBranch7.branch("2");
        sphincs256_with_SHA3_512 = aSN1ObjectIdentifierBranch7.branch("3");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch8 = aSN1ObjectIdentifierBranch6.branch("2");
        xmss = aSN1ObjectIdentifierBranch8;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch9 = aSN1ObjectIdentifierBranch8.branch("1");
        xmss_SHA256ph = aSN1ObjectIdentifierBranch9;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch10 = aSN1ObjectIdentifierBranch8.branch("2");
        xmss_SHA512ph = aSN1ObjectIdentifierBranch10;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch11 = aSN1ObjectIdentifierBranch8.branch("3");
        xmss_SHAKE128ph = aSN1ObjectIdentifierBranch11;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch12 = aSN1ObjectIdentifierBranch8.branch("4");
        xmss_SHAKE256ph = aSN1ObjectIdentifierBranch12;
        xmss_SHA256 = aSN1ObjectIdentifierBranch8.branch("5");
        xmss_SHA512 = aSN1ObjectIdentifierBranch8.branch("6");
        xmss_SHAKE128 = aSN1ObjectIdentifierBranch8.branch("7");
        xmss_SHAKE256 = aSN1ObjectIdentifierBranch8.branch("8");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch13 = aSN1ObjectIdentifierBranch6.branch("3");
        xmss_mt = aSN1ObjectIdentifierBranch13;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch14 = aSN1ObjectIdentifierBranch13.branch("1");
        xmss_mt_SHA256ph = aSN1ObjectIdentifierBranch14;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch15 = aSN1ObjectIdentifierBranch13.branch("2");
        xmss_mt_SHA512ph = aSN1ObjectIdentifierBranch15;
        xmss_mt_SHAKE128ph = aSN1ObjectIdentifierBranch13.branch("3");
        xmss_mt_SHAKE256ph = aSN1ObjectIdentifierBranch13.branch("4");
        xmss_mt_SHA256 = aSN1ObjectIdentifierBranch13.branch("5");
        xmss_mt_SHA512 = aSN1ObjectIdentifierBranch13.branch("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch16 = aSN1ObjectIdentifierBranch13.branch("7");
        xmss_mt_SHAKE128 = aSN1ObjectIdentifierBranch16;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch17 = aSN1ObjectIdentifierBranch13.branch("8");
        xmss_mt_SHAKE256 = aSN1ObjectIdentifierBranch17;
        xmss_with_SHA256 = aSN1ObjectIdentifierBranch9;
        xmss_with_SHA512 = aSN1ObjectIdentifierBranch10;
        xmss_with_SHAKE128 = aSN1ObjectIdentifierBranch11;
        xmss_with_SHAKE256 = aSN1ObjectIdentifierBranch12;
        xmss_mt_with_SHA256 = aSN1ObjectIdentifierBranch14;
        xmss_mt_with_SHA512 = aSN1ObjectIdentifierBranch15;
        xmss_mt_with_SHAKE128 = aSN1ObjectIdentifierBranch16;
        xmss_mt_with_SHAKE256 = aSN1ObjectIdentifierBranch17;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch18 = aSN1ObjectIdentifierBranch6.branch("4");
        qTESLA = aSN1ObjectIdentifierBranch18;
        qTESLA_Rnd1_I = aSN1ObjectIdentifierBranch18.branch("1");
        qTESLA_Rnd1_III_size = aSN1ObjectIdentifierBranch18.branch("2");
        qTESLA_Rnd1_III_speed = aSN1ObjectIdentifierBranch18.branch("3");
        qTESLA_Rnd1_p_I = aSN1ObjectIdentifierBranch18.branch("4");
        qTESLA_Rnd1_p_III = aSN1ObjectIdentifierBranch18.branch("5");
        qTESLA_p_I = aSN1ObjectIdentifierBranch18.branch("11");
        qTESLA_p_III = aSN1ObjectIdentifierBranch18.branch("12");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch19 = aSN1ObjectIdentifierBranch6.branch("5");
        sphincsPlus = aSN1ObjectIdentifierBranch19;
        sphincsPlus_shake_256 = aSN1ObjectIdentifierBranch19.branch("1");
        sphincsPlus_sha_256 = aSN1ObjectIdentifierBranch19.branch("2");
        sphincsPlus_sha_512 = aSN1ObjectIdentifierBranch19.branch("3");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch20 = aSN1ObjectIdentifier.branch("3");
        bc_exch = aSN1ObjectIdentifierBranch20;
        newHope = aSN1ObjectIdentifierBranch20.branch("1");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch21 = aSN1ObjectIdentifier.branch("4");
        bc_ext = aSN1ObjectIdentifierBranch21;
        linkedCertificate = aSN1ObjectIdentifierBranch21.branch("1");
        external_value = aSN1ObjectIdentifierBranch21.branch("2");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch22 = aSN1ObjectIdentifier.branch("5");
        bc_kem = aSN1ObjectIdentifierBranch22;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch23 = aSN1ObjectIdentifierBranch22.branch("1");
        pqc_kem_mceliece = aSN1ObjectIdentifierBranch23;
        mceliece348864_r3 = aSN1ObjectIdentifierBranch23.branch("1");
        mceliece348864f_r3 = aSN1ObjectIdentifierBranch23.branch("2");
        mceliece460896_r3 = aSN1ObjectIdentifierBranch23.branch("3");
        mceliece460896f_r3 = aSN1ObjectIdentifierBranch23.branch("4");
        mceliece6688128_r3 = aSN1ObjectIdentifierBranch23.branch("5");
        mceliece6688128f_r3 = aSN1ObjectIdentifierBranch23.branch("6");
        mceliece6960119_r3 = aSN1ObjectIdentifierBranch23.branch("7");
        mceliece6960119f_r3 = aSN1ObjectIdentifierBranch23.branch("8");
        mceliece8192128_r3 = aSN1ObjectIdentifierBranch23.branch("9");
        mceliece8192128f_r3 = aSN1ObjectIdentifierBranch23.branch("10");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch24 = aSN1ObjectIdentifierBranch22.branch("2");
        pqc_kem_frodo = aSN1ObjectIdentifierBranch24;
        frodokem19888r3 = aSN1ObjectIdentifierBranch24.branch("1");
        frodokem19888shaker3 = aSN1ObjectIdentifierBranch24.branch("2");
        frodokem31296r3 = aSN1ObjectIdentifierBranch24.branch("3");
        frodokem31296shaker3 = aSN1ObjectIdentifierBranch24.branch("4");
        frodokem43088r3 = aSN1ObjectIdentifierBranch24.branch("5");
        frodokem43088shaker3 = aSN1ObjectIdentifierBranch24.branch("6");
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch25 = aSN1ObjectIdentifierBranch22.branch("3");
        pqc_kem_saber = aSN1ObjectIdentifierBranch25;
        lightsaberkem128r3 = aSN1ObjectIdentifierBranch25.branch("1");
        saberkem128r3 = aSN1ObjectIdentifierBranch25.branch("2");
        firesaberkem128r3 = aSN1ObjectIdentifierBranch25.branch("3");
        lightsaberkem192r3 = aSN1ObjectIdentifierBranch25.branch("4");
        saberkem192r3 = aSN1ObjectIdentifierBranch25.branch("5");
        firesaberkem192r3 = aSN1ObjectIdentifierBranch25.branch("6");
        lightsaberkem256r3 = aSN1ObjectIdentifierBranch25.branch("7");
        saberkem256r3 = aSN1ObjectIdentifierBranch25.branch("8");
        firesaberkem256r3 = aSN1ObjectIdentifierBranch25.branch("9");
    }
}
